name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    - cron: '30 18 * * *'

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          LOCALE: "en"
          SECTION_NAME: "Waka_Create"
          COMMIT_BY_ME: "False"
          COMMIT_MESSAGE: "Commit with Waka Action"
          COMMIT_USERNAME: "Jack"
          COMMIT_EMAIL: "False"
          SHOW_UPDATED_DATE: "False"
          UPDATED_DATE_FORMAT: "False"
          SHOW_TOTAL_CODE_TIME: "True"
          SHOW_LINES_OF_CODE: "True"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_COMMIT: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_LANGUAGE: "True"
          SHOW_PROJECTS: "True"
          SHOW_OS: "True"
          SHOW_TIMEZONE: "False"
          SHOW_EDITORS: "False"
          SHOW_LANGUAGE_PER_REPO: "True"
          SHOW_SHORT_INFO: "False"
          SHOW_LOC_CHART: "False"
          IGNORED_REPOS: "False"
          SYMBOL_VERSION: "1"
          DEBUG_LOGGING: "False"
